CREATE TABLE FACULTAD
    (ID_FACULTAD VARCHAR2(8) NOT NULL
    ,NOMBRE_FACULTAD VARCHAR2(50)NOT NULL);

CREATE TABLE CARRERA
  (ID_CARRERA NUMBER(2) NOT NULL
  ,NOMBRE_CARRERA VARCHAR2(50) NOT NULL
  ,ID_FACULTAD VARCHAR2(8) NOT NULL
  ,ID_PLAN VARCHAR2(8) NOT NULL);

CREATE TABLE PLAN_ESTUDIOS
    (ID_PLAN VARCHAR2(8) NOT NULL
    ,NOMBRE_PLAN VARCHAR2(100) NOT NULL
    ,ID_CARRERA NUMBER(2) NOT NULL);
    
CREATE TABLE CURSOS
    (ID_CURSO NUMBER(10) NOT NULL
    ,NOMBRE_CURSO VARCHAR2(50) NOT NULL
    ,CREDITOS NUMBER(1) NOT NULL
    ,ID_PLAN VARCHAR2(8) NOT NULL
    ,ID_NIVEL NUMBER(2) NOT NULL
    ,ID_CARACTER_CURSO VARCHAR(1) NOT NULL);
    
CREATE TABLE CARACTER_CURSO
    (ID_CARACTER_CURSO VARCHAR(1) NOT NULL);
