create or replace PROCEDURE USP_NOM_COD
(TIPO IN VARCHAR2, NOMBRE IN ALUMNOS.NOMBRE_ALUMNO%TYPE, COD OUT NUMBER)
AS
BEGIN
    IF (TIPO = 'Profesor') THEN
        SELECT 
        COD_PROFESOR INTO COD
        FROM PROFESORES
        WHERE NOMBRE_PROFESOR = NOMBRE;
    ELSIF (TIPO = 'Alumno') THEN
        SELECT
        ID_ALUMNOS INTO COD
        FROM ALUMNOS
        WHERE NOMBRE_ALUMNO = NOMBRE;
    ELSIF (TIPO = 'Curso') THEN
        SELECT COD_CURSO INTO COD
        FROM CURSOS
        WHERE NOMBRE_CURSO = NOMBRE;
    END IF;
END;

create or replace PROCEDURE USP_VALORACION
(NOMBREALUMNO IN ALUMNOS.NOMBRE_ALUMNO%TYPE, NOMBREPROF IN PROFESORES.NOMBRE_PROFESOR%TYPE
, NOMBRECUR IN CURSOS.NOMBRE_CURSO%TYPE, COMENT IN VALORACIONES.COMENTARIO%TYPE, PUNTJ IN VALORACIONES.PUNTAJE%TYPE)
AS
    CODP NUMBER;
    CODA NUMBER;
    CODD NUMBER;
BEGIN
    USP_NOM_COD('Profesor', NOMBREPROF, CODP);
    USP_NOM_COD('Alumno', NOMBREALUMNO, CODA);
    USP_NOM_COD('Curso', NOMBRECUR, CODD);
    INSERT INTO VALORACIONES (ID_ALUMNOS,COD_PROFESOR,COD_CURSO,COMENTARIO,PUNTAJE) VALUES (CODA,CODP,CODD,COMENT,PUNTJ);
END;